image:
  file: .gitpod.Dockerfile
tasks:
  - init:
     cd .. &&
     echo 'PATH_add ~/julia-1.8.0/bin' > .envrc \
     && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> .envrc \
     && direnv allow /workspace 
  - command: python3 -m http.server 8080 -d docs/build
  - command: gp preview $(gp url 8080)
  - command: runjulia -e 'include("init.jl")'
