image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd ~ && mkdir julia && wget $JULIA_DOWNLOAD_URL | tar -xvzf -C julia \
     && echo 'PATH_add ~/julia/bin' > /workspace/.envrc \
     && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc \
     && direnv allow /workspace
  - command: cd . && julia -e 'include("init.jl")'
  - command: python3 -m http.server 8080 -d docs/build
