image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd ~ && mkdir julia && wget https://storage.googleapis.com/julialang2/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_BUGFIX_VERSION-linux-x86_64.tar.gz | tar -xvzf -C julia \
     && echo 'PATH_add ~/julia/bin' > /workspace/.envrc \
     && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc \
     && direnv allow /workspace
  - command: cd . && julia -e 'include("init.jl")'
  - command: python3 -m http.server 8080 -d docs/build
