site_name:        BitemproalPostgres
repo_url:         https://github.com/Kaeptenblaubaer/BitemporalPostgres
site_description: BitemporalPostgres provides an API for application based bitemporal transactions with Julia and Postgres DB.
site_author:      Michael Fliegner

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
